schema = 3

[mod]
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.2.2"
    hash = "sha256-j+LicPlXcB1R3oVFPa8cd4yVJLpBx+ca5gXmHqOJSN8="
  [mod."golang.org/x/sys"]
    version = "v0.27.0"
    hash = "sha256-BXQcF9RrJ55Pq7Nl67TeFGkgkyuKkQ8hHKN4/L4ggWc="
